// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_dense_lsconjgrad
Rcpp::List solve_dense_lsconjgrad(Rcpp::List input);
RcppExport SEXP _L0adri1_0_solve_dense_lsconjgrad(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_dense_lsconjgrad(input));
    return rcpp_result_gen;
END_RCPP
}
// solve_sparse_LDLT
Rcpp::List solve_sparse_LDLT(Rcpp::List input);
RcppExport SEXP _L0adri1_0_solve_sparse_LDLT(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sparse_LDLT(input));
    return rcpp_result_gen;
END_RCPP
}
// solve_sparse_lsconjgrad
Rcpp::List solve_sparse_lsconjgrad(Rcpp::List input);
RcppExport SEXP _L0adri1_0_solve_sparse_lsconjgrad(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sparse_lsconjgrad(input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_L0adri1_0_solve_dense_lsconjgrad", (DL_FUNC) &_L0adri1_0_solve_dense_lsconjgrad, 1},
    {"_L0adri1_0_solve_sparse_LDLT", (DL_FUNC) &_L0adri1_0_solve_sparse_LDLT, 1},
    {"_L0adri1_0_solve_sparse_lsconjgrad", (DL_FUNC) &_L0adri1_0_solve_sparse_lsconjgrad, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_L0adri1_0(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
