# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_dense_lsconjgrad <- function(input) {
    .Call('_L0adri1_0_solve_dense_lsconjgrad', PACKAGE = 'L0adri1.0', input)
}

solve_sparse_LDLT <- function(input) {
    .Call('_L0adri1_0_solve_sparse_LDLT', PACKAGE = 'L0adri1.0', input)
}

solve_sparse_lsconjgrad <- function(input) {
    .Call('_L0adri1_0_solve_sparse_lsconjgrad', PACKAGE = 'L0adri1.0', input)
}

